-- Create the sales_data table
CREATE TABLE sales_data (
   id bigint generated by default as identity primary key,
   date date,
   product text,
   channel text,
   orders numeric,
   revenue numeric,
   cost numeric,
   visitors numeric,
   customers numeric
);

-- Enable RLS for security
ALTER TABLE sales_data ENABLE ROW LEVEL SECURITY;

-- Allow public read access (Modify this for production!)
CREATE POLICY "Allow public read access" ON sales_data FOR SELECT USING (true);
